import { useId, useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity, ArrowRight, ArrowUpRight, Bookmark, Clock3, Compass, RefreshCw, ShieldCheck, SlidersHorizontal, Sparkles } from 'lucide-react';
import { useMarket } from '../legacy/MarketContext';
import { useWatchlist } from '../legacy/WatchlistContext';
import { useAuth } from '../legacy/AuthContext';
import WatchlistStar from '../legacy/components/WatchlistStar';
import { Change, EmptyState, ErrorState, Loading, PageHeading, Panel } from '../components/ui';
import { formatNumber, formatPrice, formatStamp, number, symbolPath } from '../lib/market';
import { validSeries, seriesPath } from '../lib/series';
import { useResource } from '../lib/useResource';

interface IndexQuote { name: string; last?: number; change_pct?: number; spark?: number[]; spark_dates?: string[]; as_of?: string; source?: string }
interface Mover { ticker: string; last?: number; change_pct?: number; spark?: number[] }
interface Dashboard { indices?: IndexQuote[]; movers?: Mover[]; movers_market?: string; pulse_names?: string[]; market_open?: boolean; as_of?: string }
interface Plan { symbol: string; side?: string; score?: number; lifecycle?: string; why?: string }
interface Signals { as_of?: string; data_status?: { status?: string; required_inputs_complete?: boolean; observed_at?: string }; setups?: { plans?: Plan[]; radar_size?: number }; regime?: { overall?: string; dir?: string; breadth?: { adv?: number; dec?: number }; vol?: { label?: string } } }

function Spark({ values, className = '' }: { values: unknown; className?: string }) {
  const series = validSeries(values);
  if (!series.length) return <span className="an-muted">—</span>;
  const positive = series.at(-1)! >= series[0];
  return <svg className={`an-spark ${positive ? 'is-up' : 'is-down'} ${className}`} viewBox="0 0 110 34" aria-label={series.length > 1 && series[0] !== 0 ? `${((series.at(-1)! / series[0] - 1) * 100).toFixed(2)}% across ${series.length} daily observations` : 'Recent price trend unavailable'} role="img"><path d={seriesPath(series, 110, 34, 3)} fill="none" stroke="currentColor" strokeWidth="1.8" vectorEffect="non-scaling-stroke"/></svg>;
}
function MarketChart({ index }: { index: IndexQuote | undefined }) {
  const [range, setRange] = useState(30);
  const id = useId().replaceAll(':', '');
  const full = validSeries(index?.spark);
  const values = full.slice(-range);
  const dates = index?.spark_dates?.length === full.length ? index.spark_dates.slice(-range) : [];
  const path = seriesPath(values, 760, 210, 20);
  const low = Math.min(...values), high = Math.max(...values);
  const provenance = `${index?.source || 'Provider'} · ${formatStamp(index?.as_of)}`;
  return <><div className="an-chart-toolbar"><div className="an-chart-quote"><strong>{formatNumber(index?.last)}</strong><Change value={index?.change_pct}/><span>latest snapshot</span></div><div className="an-segments" aria-label="Chart observations">{[10,20,30].map(count => <button key={count} aria-pressed={range === count} onClick={() => setRange(count)}>{count}<span> closes</span></button>)}</div></div>{values.length ? <div className="an-market-chart"><svg viewBox="0 0 830 242" role="img" aria-label={`${index?.name} recent closing prices, ${values.length} observations. ${provenance}.`}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#75d9d4" stopOpacity=".2"/><stop offset="100%" stopColor="#75d9d4" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3,4].map(i => <g key={i}><line x1="0" x2="760" y1={20+i*42.5} y2={20+i*42.5} stroke="#263137" strokeDasharray="3 5"/><text x="775" y={24+i*42.5} fill="#8b979f" fontSize="11">{formatNumber(high-(high-low)*i/4,0)}</text></g>)}<path d={`${path} L760,210 L0,210 Z`} fill={`url(#${id})`}/><path d={path} stroke="#8ee5df" strokeWidth="2" fill="none" vectorEffect="non-scaling-stroke"/><text x="0" y="237" fill="#8b979f" fontSize="11">{dates.length ? formatStamp(dates[0]) : 'Earlier observations (dates unavailable)'}</text><text x="760" y="237" textAnchor="end" fill="#8b979f" fontSize="11">{dates.length ? formatStamp(dates.at(-1)) : 'Latest available (date unavailable)'}</text></svg></div> : <EmptyState title="Price history unavailable" description="The latest quote is shown above. History will appear when the provider supplies it."/>}<div className="an-chart-note"><span><span className="an-dot"/>{index?.name || 'Index'} · daily closing observations</span><span>{provenance}</span></div></>;
}
function WatchlistPreview() {
  const { currentUser } = useAuth();
  const { symbols, loadError, loading, marketOf } = useWatchlist() as { symbols: string[]; loadError: string | null; loading: boolean; marketOf: (symbol: string) => string };
  return <Panel title="Your watchlist" action={<Link className="an-text-link" to="/watchlist">Open <ArrowUpRight size={14}/></Link>} className="an-watch-preview">{loading ? <Loading label="Loading watchlist"/> : loadError ? <ErrorState message={loadError}/> : symbols.length ? <div className="an-preview-list">{symbols.slice(0,5).map(symbol => <Link key={symbol} to={symbolPath(symbol,marketOf(symbol))}><span className="an-symbol-icon" aria-hidden="true">{symbol.slice(0,2)}</span><strong>{symbol}</strong><ArrowUpRight size={15}/></Link>)}</div> : <div className="an-watch-empty"><div className="an-watch-art"><Bookmark size={25}/><span>+</span></div><h3>Keep your best ideas close.</h3><p>{currentUser ? 'Build a focused shortlist. Pick a stock to start tracking your research.' : 'Save the stocks you follow and pick up where you left off.'}</p><Link className="an-button" to={currentUser ? '/watchlist' : '/login?mode=signup'} state={{ from: { pathname: '/watchlist' } }}>{currentUser ? 'Build your watchlist' : 'Create your workspace'}<ArrowRight size={14}/></Link></div>}</Panel>;
}
export default function Today({ home = false }: { home?: boolean }) {
  const { market } = useMarket();
  const dashboard = useResource<Dashboard>(`/api/dashboard?market=${market}`, 120000);
  const signals = useResource<Signals>(`/api/signals?market=${market}`, 0);
  const [selected, setSelected] = useState('');
  const indices = dashboard.data?.indices || [];
  const leadNames = dashboard.data?.pulse_names || (market === 'US' ? ['S&P 500','NASDAQ 100'] : ['NIFTY 50','BANKNIFTY']);
  const leads = indices.filter(index => leadNames.includes(index.name));
  const featured = indices.find(index => index.name === selected) || leads[0];
  const tiles = [...leads, ...indices.filter(index => market === 'US' ? ['VIX','US VIX','USD/INR'].includes(index.name) : ['INDIA VIX','USD/INR'].includes(index.name))].slice(0,4);
  const movers = dashboard.data?.movers || [];
  const source = signals.data?.data_status;
  const complete = source?.required_inputs_complete === true && ['fresh','last_session'].includes(source?.status || '') && !signals.error;
  const plans = complete ? [...(signals.data?.setups?.plans || [])].filter(plan => plan.symbol && !['forming','extended','invalidated'].includes(plan.lifecycle || '')).sort((a,b) => (number(b.score) || 0)-(number(a.score) || 0)).slice(0,3) : [];
  const regime = signals.data?.regime;
  const advancing = number(regime?.breadth?.adv), declining = number(regime?.breadth?.dec);
  // Missing provider counts are unknown, not zero: do not imply one-sided breadth.
  const total = advancing !== null && declining !== null && advancing >= 0 && declining >= 0
    ? advancing + declining : 0;
  const date = new Intl.DateTimeFormat('en-IN', { weekday:'long', day:'numeric', month:'long', timeZone:'Asia/Kolkata' }).format(new Date());
  return <div className="an-today"><PageHeading as={home ? 'h2' : 'h1'} eyebrow={<><span className="an-gold-dot"/>YOUR DAILY MARKET BRIEF</>} title="Today" description={`${date} · ${market === 'US' ? 'US' : 'Indian'} market research`} actions={<><span className="an-session-pill"><span className={`an-dot ${dashboard.data?.market_open ? '' : 'is-closed'}`}/>{dashboard.loading ? 'Checking session' : dashboard.error && !dashboard.data ? 'Session unavailable' : dashboard.data?.market_open === true ? 'Market open' : dashboard.data?.market_open === false ? 'Market closed' : 'Session unavailable'}</span><button className="an-icon-button an-bordered" aria-label="Refresh dashboard" disabled={dashboard.refreshing || signals.refreshing} onClick={() => { dashboard.refresh(); signals.refresh(); }}><RefreshCw size={16} className={dashboard.refreshing ? 'an-spin' : ''}/></button></>}/>
    {dashboard.error && <ErrorState message={dashboard.data ? 'Refresh failed. Showing the previous market snapshot.' : dashboard.error} retry={dashboard.refresh}/>}
    <div className="an-index-grid">{dashboard.loading ? Array.from({length:4},(_,i) => <div className="an-index-card" key={i}><Loading label="Loading quote"/></div>) : tiles.map(index => <button className={`an-index-card ${featured?.name === index.name ? 'is-selected' : ''}`} key={index.name} onClick={() => setSelected(index.name)} aria-pressed={featured?.name === index.name}><div className="an-index-name">{index.name}<span>{index.name.includes('VIX') ? 'VOLATILITY' : index.name.includes('USD') ? 'CURRENCY' : market === 'US' ? 'US' : 'NSE'}</span></div><div className="an-index-value">{formatNumber(index.last)}<Spark values={index.spark}/></div><Change value={index.change_pct}/><span className="an-index-caption"> vs previous close</span></button>)}</div>
    <div className="an-today-grid"><div className="an-today-main"><Panel className="an-overview-panel" title="Market overview" subtitle="Index snapshot and trend." action={<div className="an-index-tabs">{leads.map(index => <button aria-pressed={featured?.name === index.name} key={index.name} onClick={() => setSelected(index.name)}>{index.name}</button>)}</div>}>{dashboard.loading ? <Loading label="Loading market history"/> : <MarketChart index={featured}/>}</Panel>
    <Panel title="On the radar" subtitle="Scored setups." action={<Link className="an-text-link" to="/signals">All signals <ArrowUpRight size={14}/></Link>} className="an-radar-panel">{signals.loading ? <Loading label="Loading research candidates"/> : signals.error ? <ErrorState message="The signal feed could not refresh. Open Signals to retry." retry={signals.refresh}/> : plans.length ? <div className="an-radar-list">{plans.map((plan,index) => <Link to={symbolPath(plan.symbol,market)} key={`${plan.symbol}-${plan.side}`} className="an-radar-row"><span className="an-radar-number">0{index+1}</span><div className="an-radar-name"><strong>{plan.symbol}</strong><span>{plan.lifecycle ? plan.lifecycle.replaceAll('_',' ') : 'Published research'} · {market === 'US' ? 'US' : 'NSE'}</span></div><span className={`an-direction ${plan.side === 'LONG' ? 'an-positive' : 'an-negative'}`}>{plan.side === 'LONG' ? '↗' : '↘'} {plan.side}</span><div className="an-score"><span>Quality</span><strong>{formatNumber(plan.score,0)}<small>/100</small></strong></div><ArrowUpRight size={17}/></Link>)}</div> : <EmptyState title={complete ? 'No qualifying setups in this snapshot' : 'Waiting for complete market evidence'} description="Check Signals for the latest evidence." action={<Link className="an-text-link" to="/signals">Review signal evidence <ArrowRight size={14}/></Link>}/>}<div className="an-panel-footnote"><Clock3 size={13}/>{formatStamp(source?.observed_at || signals.data?.as_of)} · research, not a recommendation</div></Panel>
    <Panel title="Stocks in motion" subtitle="Latest available movers." action={<Link className="an-text-link" to="/screener">Screener <ArrowUpRight size={14}/></Link>}><div className="an-table-wrap"><table className="an-movers-table"><thead><tr><th>COMPANY</th><th>LAST PRICE</th><th>CHANGE</th><th className="an-trend-column">RECENT TREND</th><th><span className="an-sr-only">Save (sign in required)</span></th></tr></thead><tbody>{movers.map(mover => <tr key={mover.ticker}><td><Link to={symbolPath(mover.ticker,dashboard.data?.movers_market || market)}><span className="an-symbol-icon" aria-hidden="true">{mover.ticker.slice(0,2)}</span><span><strong>{mover.ticker}</strong><small>{(dashboard.data?.movers_market || market) === 'US' ? 'US equity' : 'NSE equity'}</small></span></Link></td><td>{formatPrice(mover.last,dashboard.data?.movers_market || market)}</td><td><Change value={mover.change_pct}/></td><td className="an-trend-column"><Spark values={mover.spark}/></td><td><WatchlistStar symbol={mover.ticker} market={dashboard.data?.movers_market || market} size={16}/></td></tr>)}</tbody></table></div>{dashboard.loading && <Loading label="Loading movers"/>}{!dashboard.loading && !movers.length && <EmptyState title="Mover snapshot unavailable" description="Refresh the dashboard to check the provider again."/>}</Panel></div>
    <aside className="an-today-aside"><Panel className="an-regime-panel" title="The market lens" action={<Activity size={16}/>}><div className="an-regime-orbit"><span/><span/><span/><ShieldCheck size={28}/></div><div className="an-regime-title">{regime?.overall ? regime.overall.replaceAll('-',' ').toLowerCase() : 'Awaiting context'}</div><p>{regime?.overall === 'RISK-OFF' ? 'A selective market. Look for confirmation and keep risk in view.' : regime?.overall === 'RISK-ON' ? 'Supportive market conditions. Validate each idea on its own evidence.' : 'Read the broader market before narrowing your shortlist.'}</p><div className="an-regime-details"><div><span>Directional bias</span><strong>{regime?.dir?.toUpperCase() || 'Unavailable'}</strong></div><div><span>Volatility regime</span><strong>{regime?.vol?.label || 'Unavailable'}</strong></div></div>{total > 0 && <div className="an-breadth"><div><span>Tracked breadth</span><strong>{Math.round((advancing || 0)/total*100)}% advancing</strong></div><div className="an-breadth-bar"><span style={{width:`${(advancing || 0)/total*100}%`}}/></div><small>{advancing} advancing · {declining} declining · tracked sample</small></div>}<Link className="an-text-link" to="/signals">Understand the regime <ArrowRight size={14}/></Link></Panel><WatchlistPreview/><Panel title="Go one level deeper" className="an-quick-tools">{[{path:'/delivery-radar',title:'Delivery radar',detail:'Participation behind the price',icon:Activity},{path:'/sectors',title:'Sector rotation',detail:'Follow market leadership',icon:Compass},{path:'/screener',title:'Stock screener',detail:'Find ideas that fit your process',icon:SlidersHorizontal}].map(({path,title,detail,icon:Icon}) => <Link key={path} to={path}><span className="an-tool-icon"><Icon size={17}/></span><span><strong>{title}</strong><small>{detail}</small></span><ArrowUpRight size={15}/></Link>)}</Panel><div className="an-research-note"><Sparkles size={17}/><p>Explore more research.<br/><Link to="/learn">Build your process <ArrowUpRight size={12}/></Link></p></div></aside></div>
  </div>;
}
