import {readFileSync,writeFileSync} from 'node:fs';
function change(path, fn) { const url = new URL(`../${path}`,import.meta.url); writeFileSync(url,fn(readFileSync(url,'utf8'))); }
change('src/pages/Today.tsx',text=>text.replace('Sparkles, Star, Zap','Sparkles'));
for(const page of ['Signals','Watchlist','Analyse']) change(`src/pages/${page}.tsx`, text=>text.replace('<main className=', '<div className=').replace('</main>','</div>'));
change('src/lib/useResource.ts',text=>text.replace('stopped = true; latest.current++; controller?.abort();','stopped = true; controller?.abort();'));
change('src/pages/Watchlist.tsx',text=>text.replace('const previousSymbols = useRef(symbolKey);','const previousSymbols = useRef(symbolKey);\n  const refreshQuotes = quotes.refresh;').replace('if (quoteUrl) quotes.refresh();','if (quoteUrl) refreshQuotes();').replace('[quoteUrl, quotes.refresh, symbolKey]','[quoteUrl, refreshQuotes, symbolKey]'));
change('src/pages/Signals.tsx',text=>text.replace('lazy, Suspense, useMemo, useState','lazy, Suspense, useState').replace("const filteredPublished = useMemo(() => filterSignals(published, { direction, lifecycle, query, lane: 'published' }) as SignalPlan[], [published, direction, lifecycle, query]);", "const filteredPublished = filterSignals(published, { direction, lifecycle, query, lane: 'published' }) as SignalPlan[];").replace("const filteredEarly = useMemo(() => filterSignals(early, { direction, lifecycle, query, lane: 'early' }) as SignalPlan[], [early, direction, lifecycle, query]);", "const filteredEarly = filterSignals(early, { direction, lifecycle, query, lane: 'early' }) as SignalPlan[];"));
change('src/pages/Analyse.tsx',text=>text.replace('formatNumber, formatPrice, formatStamp','formatNumber, formatPrice, formatStamp, number').replace(/const latestFinite = \(values\?: Array<number \| null>\) => \{[\s\S]*?\n\};/, 'const latestFinite = (values?: Array<number | null>) => number(values?.at(-1));').replace("const n = typeof value === 'number' ? value : Number(value);",'const n = number(value);').replace('return Number.isFinite(n) ?','return n !== null ?').replace('} today</span>','} vs previous close</span>'));
change('src/legacy/AuthContext.jsx',text=>text.replace('{!loading && children}', '{loading ? <div className="an-loading" role="status">Restoring your workspace…</div> : children}'));
change('package.json',text=>{ const data=JSON.parse(text); data.scripts.test='node --test --test-isolation=none tests/*.test.mjs src/pages/*.test.js src/pages/*.test.mjs'; return JSON.stringify(data,null,2)+'\n'; });
