import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '../..');
const configPath = path.join(root, 'vercel.json');
const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
config.builds.find(build => build.use === '@vercel/static-build').src = 'alpha-nova-next/package.json';
const python = config.builds.find(build => build.use === '@vercel/python');
if (!python.config.excludeFiles.includes('alpha-nova-next/**')) python.config.excludeFiles = python.config.excludeFiles.replace('{', '{alpha-nova-next/**,');
for (const route of config.routes) if (route.dest?.startsWith('/web/')) route.dest = route.dest.replace('/web/', '/alpha-nova-next/');
fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');
const ignorePath = path.join(root, '.vercelignore');
const ignore = fs.readFileSync(ignorePath, 'utf8');
if (!ignore.includes('alpha-nova-next/dist/')) fs.appendFileSync(ignorePath, '\n# The rebuilt frontend is the production entry point.\nweb/\nalpha-nova-next/dist/\nalpha-nova-next/tests/\nalpha-nova-next/node_modules/\n');
const releaseName = process.env.ALPHANOVA_RELEASE_NAME || 'alpha-nova-next-release';
if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(releaseName)) throw new Error('Invalid release directory name.');
const stage = path.join(root, '.tmp', releaseName);
if (fs.existsSync(stage)) throw new Error('Release directory already exists; inspect before replacing it.');
fs.mkdirSync(stage, {recursive:true});
const copy = (rel, filter) => fs.cpSync(path.join(root,rel),path.join(stage,rel),{recursive:true,filter});
copy('api', source => {
  const rel=path.relative(path.join(root,'api'),source).replaceAll('\\','/');
  if (!rel) return true;
  if (/(^|\/)(?:__pycache__|\.pytest_cache|scripts|fundamentals_function)(\/|$)/.test(rel)) return false;
  if (fs.statSync(source).isDirectory()) return true;
  return (rel.endsWith('.py') && !/(^|\/)test_/.test(rel)) || rel === 'requirements.txt';
});
for (const rel of ['package.json','package-lock.json','tsconfig.json','vite.config.ts','index.html','src','public','scripts/generate-seo-pages.mjs']) copy('alpha-nova-next/'+rel, source => !/\.test\.(js|mjs|ts|tsx)$/.test(source));
copy('vercel.json');
copy('.vercel/project.json');
fs.writeFileSync(path.join(stage,'.vercelignore'),'**/node_modules/\n**/__pycache__/\n**/*.pyc\n**/.env*\nalpha-nova-next/dist/\n');
console.log('Prepared allowlisted release:',stage);
