import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './legacy/index.css';
import './legacy/App.css';
import './legacy/components/ui/ui.css';
import './styles.css';
import './magic/magic.css';
import './readability.css';
import App from './App';
window.addEventListener('beforeinstallprompt', event => { event.preventDefault(); (window as Window & { __anInstallPrompt?: Event }).__anInstallPrompt = event; window.dispatchEvent(new Event('an-install-ready')); });
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
if (import.meta.env.PROD && 'serviceWorker' in navigator) window.addEventListener('load', () => { navigator.serviceWorker.register('/sw.js').catch(() => {}); });
